### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by AYSEGULKZC** [rpkgs/VIC5#1]
I run VIC5 model successfully. I would like to perform Lohmann function for routing phase.  I followed the method for this in the given link:  https://github.com/Sibada/VICmodel/blob/master/R/routing.R
I could generate unit hydrograph (the first part), but Lohmann_conv function couldn't run. The given problem was about aux_Lohmann_conv function.  I tried to fix it. I found this :
https://github.com/Sibada/VICmodel/blob/master/R/RcppExports.R
Here,  PACKAGE = 'VICmodel' which is not available now. I tried to change the package name by looking at VIC5 source documents. In this case, the given problem was about "_VICmodel_aux_Lohmann_conv". It couldn't find it.
I couldn't solve the problem. Could you please help me for this step?

**Comment by kongdd** [comment]
rename `aux_Lohmann_conv` to `VIC5::aux_Lohmann_conv` should fix this issue.
